# -*- coding: utf-8 -*-
"""
Runs router.
Retrieves metrics, parameters, pipeline step checkpoints, and artifacts for active/past runs.
"""
from __future__ import annotations

import logging
import uuid
from typing import List
from fastapi import APIRouter, Depends, HTTPException, WebSocket, WebSocketDisconnect
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
import asyncio
import json

from db.models import Run as DBRun, Metric as DBMetric, Parameter as DBParameter, PipelineStep as DBPipelineStep, Artifact as DBArtifact
from ets.api.routes.datasets import get_db

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/experiments/{experiment_id}")
async def list_runs_for_experiment(
    experiment_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """List all runs executed for a specific experiment."""
    stmt = select(DBRun).where(DBRun.experiment_id == experiment_id).order_by(DBRun.created_at.desc())
    res = await db.execute(stmt)
    runs = res.scalars().all()
    return [
        {
            "id": str(r.id),
            "run_number": r.run_number,
            "status": r.status,
            "error_message": r.error_message,
            "started_at": r.started_at.isoformat() if r.started_at else None,
            "completed_at": r.completed_at.isoformat() if r.completed_at else None,
            "duration_seconds": r.duration_seconds,
            "created_at": r.created_at.isoformat(),
        }
        for r in runs
    ]


@router.get("/{run_id}")
async def get_run_details(
    run_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """Get core configuration snapshot, environment details, and execution lifecycle status for a run."""
    stmt = select(DBRun).where(DBRun.id == run_id)
    res = await db.execute(stmt)
    r = res.scalar_one_or_none()
    if not r:
        raise HTTPException(status_code=404, detail="Run not found")
        
    return {
        "id": str(r.id),
        "experiment_id": str(r.experiment_id),
        "run_number": r.run_number,
        "status": r.status,
        "config_snapshot": r.config_snapshot,
        "environment_json": r.environment_json,
        "error_message": r.error_message,
        "started_at": r.started_at.isoformat() if r.started_at else None,
        "completed_at": r.completed_at.isoformat() if r.completed_at else None,
        "duration_seconds": r.duration_seconds,
        "created_at": r.created_at.isoformat(),
    }


@router.get("/{run_id}/metrics")
async def get_run_metrics(
    run_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """Get all logged sparse/dense evaluation metrics for a run."""
    stmt = select(DBMetric).where(DBMetric.run_id == run_id).order_by(DBMetric.timestamp.asc())
    res = await db.execute(stmt)
    metrics = res.scalars().all()
    return [
        {
            "key": m.key,
            "value": m.value,
            "step": m.step,
            "timestamp": m.timestamp.isoformat(),
        }
        for m in metrics
    ]


@router.get("/{run_id}/parameters")
async def get_run_parameters(
    run_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """Get all recorded parameters and configurations for a run."""
    stmt = select(DBParameter).where(DBParameter.run_id == run_id).order_by(DBParameter.key.asc())
    res = await db.execute(stmt)
    params = res.scalars().all()
    return [
        {
            "key": p.key,
            "value": p.value,
        }
        for p in params
    ]


@router.get("/{run_id}/steps")
async def get_run_steps(
    run_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """Get step-based checkpoint status updates for monitoring pipeline progress and failures."""
    stmt = select(DBPipelineStep).where(DBPipelineStep.run_id == run_id).order_by(DBPipelineStep.id.asc())
    res = await db.execute(stmt)
    steps = res.scalars().all()
    return [
        {
            "step_name": s.step_name,
            "status": s.status,
            "outputs": s.outputs,
            "completed_at": s.completed_at.isoformat() if s.completed_at else None,
        }
        for s in steps
    ]


@router.get("/{run_id}/artifacts")
async def get_run_artifacts(
    run_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """Get all registered artifacts generated by a run."""
    stmt = select(DBArtifact).where(DBArtifact.run_id == run_id).order_by(DBArtifact.created_at.desc())
    res = await db.execute(stmt)
    artifacts = res.scalars().all()
    return [
        {
            "id": str(a.id),
            "name": a.name,
            "storage_backend": a.storage_backend,
            "storage_key": a.storage_key,
            "file_size_bytes": a.file_size_bytes,
            "content_type": a.content_type,
            "artifact_type": a.artifact_type,
            "metadata_json": a.metadata_json,
            "created_at": a.created_at.isoformat(),
        }
        for a in artifacts
    ]


from fastapi.responses import FileResponse
import os

@router.get("/{run_id}/artifacts/{artifact_id}/download")
async def download_run_artifact(
    run_id: uuid.UUID,
    artifact_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """Download/view a registered artifact file by its ID."""
    stmt = select(DBArtifact).where(DBArtifact.id == artifact_id, DBArtifact.run_id == run_id)
    res = await db.execute(stmt)
    artifact = res.scalar_one_or_none()
    if not artifact:
        raise HTTPException(status_code=404, detail="Artifact not found")
    
    file_path = artifact.storage_key
    if not os.path.exists(file_path):
        # Fallback to check relative path in REPORT_DIR
        from vn_regime_transfer.config import REPORT_DIR
        fallback_path = os.path.join(REPORT_DIR, artifact.name)
        if os.path.exists(fallback_path):
            file_path = fallback_path
        else:
            raise HTTPException(status_code=404, detail=f"Artifact file not found on disk: {file_path}")
    
    return FileResponse(
        path=file_path,
        media_type=artifact.content_type,
        filename=artifact.name
    )


@router.websocket("/{run_id}/stream")
async def run_metrics_stream(websocket: WebSocket, run_id: str):
    """
    WebSocket endpoint for real-time telemetry streaming.
    Subscribes to the EventBus and streams metrics to the connected client.
    """
    from ets.api.main import event_bus
    
    await websocket.accept()
    queue = asyncio.Queue()

    async def event_handler(event):
        await queue.put(event)

    channel_name = f"run:{run_id}"
    await event_bus.subscribe(channel_name, event_handler)
    
    try:
        while True:
            # Wait for events from the queue (put by the event_handler)
            event = await asyncio.wait_for(queue.get(), timeout=30.0)
            await websocket.send_text(event.to_json())
    except asyncio.TimeoutError:
        # Send a ping/keepalive message or close
        try:
            await websocket.send_text(json.dumps({"name": "ping", "data": {}}))
        except WebSocketDisconnect:
            pass
    except WebSocketDisconnect:
        logger.info(f"WebSocket client disconnected from {channel_name}")
    finally:
        # In a complete implementation, we'd unsubscribe here.
        # For simplicity, LocalEventBus currently doesn't have an explicit unsubscribe method,
        # but it uses weak references or handles it gracefully.
        pass


@router.delete("/{run_id}")
async def delete_run(
    run_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """Delete a run, its database records, and its artifact files from disk."""
    import os
    import shutil
    
    # 1. Fetch the run
    stmt = select(DBRun).where(DBRun.id == run_id)
    res = await db.execute(stmt)
    run = res.scalar_one_or_none()
    if not run:
        raise HTTPException(status_code=404, detail="Run not found")

    # 2. Fetch and delete artifacts from disk
    stmt_art = select(DBArtifact).where(DBArtifact.run_id == run_id)
    res_art = await db.execute(stmt_art)
    artifacts = res_art.scalars().all()
    
    # Track directories to delete
    run_dirs_to_delete = set()
    for art in artifacts:
        # Delete file if exists
        file_path = art.storage_key
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
            except Exception as e:
                logger.warning("Failed to delete artifact file %s: %s", file_path, e)
        
        # Deduce per-run directory from metadata
        if art.metadata_json and isinstance(art.metadata_json, dict):
            run_dir = art.metadata_json.get("run_dir")
            if run_dir:
                run_dirs_to_delete.add(run_dir)

    # Delete snapshot run directories if they are empty
    for run_dir in run_dirs_to_delete:
        if os.path.isdir(run_dir):
            try:
                shutil.rmtree(run_dir)
            except Exception as e:
                logger.warning("Failed to remove run directory %s: %s", run_dir, e)

    # 3. Delete DB records associated with the run (metrics, params, steps, artifacts)
    from db.models import Metric, Parameter, PipelineStep, Artifact
    from sqlalchemy import delete
    
    await db.execute(delete(Metric).where(Metric.run_id == run_id))
    await db.execute(delete(Parameter).where(Parameter.run_id == run_id))
    await db.execute(delete(PipelineStep).where(PipelineStep.run_id == run_id))
    await db.execute(delete(Artifact).where(Artifact.run_id == run_id))
    await db.execute(delete(DBRun).where(DBRun.id == run_id))
    
    await db.commit()
    logger.info("Successfully deleted Run #%d (%s) and all its data", run.run_number, run_id)
    return {"status": "success", "message": f"Run #{run.run_number} deleted successfully"}
